#include "openscadgenerator.h"

#include <QStringList>

QString OpenScadGenerator::generate(const SceneDocument &scene)
{
    QString code;

    code += "// Generated by OpenSCAD Visual Editor Prototype\n";
    code += "// UI -> OpenSCAD code\n\n";

    if (scene.isEmpty()) {
        code += "// Add shapes from the left panel.\n";
        return code;
    }

    bool hasAddShapes = false;
    bool hasSubtractShapes = false;
    for (const ShapeNode &shape : scene.shapes()) {
        if (shape.booleanMode == ShapeNode::Subtract)
            hasSubtractShapes = true;
        else
            hasAddShapes = true;
    }

    hasSubtractShapes = hasAddShapes && hasSubtractShapes;
    code += hasSubtractShapes ? "difference() {\n    union() {\n" : "union() {\n";

    for (const ShapeNode &shape : scene.shapes()) {
        if (hasSubtractShapes && shape.booleanMode == ShapeNode::Subtract)
            continue;

        const QString shapeCode = shapeToOpenScad(shape);
        const QStringList lines = shapeCode.split('\n');

        for (const QString &line : lines) {
            if (!line.trimmed().isEmpty())
                code += (hasSubtractShapes ? "        " : "    ") + line + "\n";
        }
    }

    if (hasSubtractShapes) {
        code += "    }\n";

        for (const ShapeNode &shape : scene.shapes()) {
            if (shape.booleanMode != ShapeNode::Subtract)
                continue;

            const QString shapeCode = shapeToOpenScad(shape);
            const QStringList lines = shapeCode.split('\n');

            for (const QString &line : lines) {
                if (!line.trimmed().isEmpty())
                    code += "    " + line + "\n";
            }
        }
    }

    code += "}\n";

    return code;
}

QString OpenScadGenerator::shapeToOpenScad(const ShapeNode &shape)
{
    QString code;

    code += QString("translate([%1, %2, %3])\n")
                .arg(shape.position.x())
                .arg(shape.position.y())
                .arg(shape.position.z());

    code += QString("rotate([%1, %2, %3])\n")
                .arg(shape.rotation.x())
                .arg(shape.rotation.y())
                .arg(shape.rotation.z());

    if (shape.type == ShapeNode::Cube) {
        code += QString("cube([%1, %2, %3], center=true);\n")
                    .arg(shape.size.x())
                    .arg(shape.size.y())
                    .arg(shape.size.z());
    } else if (shape.type == ShapeNode::Sphere) {
        code += QString("sphere(r=%1);\n")
                    .arg(shape.radius);
    } else if (shape.type == ShapeNode::Cylinder) {
        code += QString("cylinder(h=%1, r=%2, center=true);\n")
                    .arg(shape.height)
                    .arg(shape.radius);
    }

    return code;
}
