#include "openscadgenerator.h"

#include <QStringList>

void OpenScadGenerator::appendShape(QString *code, const ShapeNode &shape, const QString &indent)
{
    const QString shapeCode = shapeToOpenScad(shape);
    const QStringList lines = shapeCode.split('\n');

    for (const QString &line : lines) {
        if (!line.trimmed().isEmpty())
            *code += indent + line + "\n";
    }
}

QString OpenScadGenerator::generate(const SceneDocument &scene)
{
    return generateWithSourceMap(scene, nullptr);
}

QString OpenScadGenerator::generateWithSourceMap(const SceneDocument &scene, QVector<SourceRange> *ranges)
{
    QString code;
    if (ranges)
        ranges->clear();

    code += "// Generated by OpenSCAD Visual Editor Prototype\n";
    code += "// UI -> OpenSCAD code\n\n";

    appendSceneModule(&code, scene, ranges);
    return code;
}

static QString treeOperationName(SceneDocument::TreeNode::Operation operation)
{
    if (operation == SceneDocument::TreeNode::Difference)
        return "difference";
    if (operation == SceneDocument::TreeNode::Intersection)
        return "intersection";
    return "union";
}

// Collect parameter variables and return the module signature string "name(p1=e1, p2=e2)".
static QString moduleSignature(const SceneDocument::TreeNode &moduleNode)
{
    QStringList params;
    for (const SceneDocument::TreeNode &child : moduleNode.children) {
        if (child.type == SceneDocument::TreeNode::Variable && child.isParameter) {
            const QString expr = child.variableExpression.trimmed().isEmpty()
                                     ? QString::number(child.variableValue)
                                     : child.variableExpression.trimmed();
            params.append(QString("%1 = %2").arg(child.variableName, expr));
        }
    }
    const QString name = moduleNode.moduleName.trimmed().isEmpty()
                             ? QStringLiteral("scene_model")
                             : moduleNode.moduleName.trimmed();
    return params.isEmpty() ? name + "()" : name + "(" + params.join(", ") + ")";
}

void OpenScadGenerator::appendSceneModule(QString *code, const SceneDocument &scene, QVector<SourceRange> *ranges)
{
    // --- 1. Emit global variables (Variable children of root) ---
    for (const SceneDocument::TreeNode &child : scene.treeRoot().children) {
        if (child.type == SceneDocument::TreeNode::Variable) {
            const int start = code->size();
            const QString expr = child.variableExpression.trimmed().isEmpty()
                                     ? QString::number(child.variableValue)
                                     : child.variableExpression.trimmed();
            *code += QString("%1 = %2;\n").arg(child.variableName, expr);
            if (ranges)
                ranges->append({child.id, start, code->size() - start});
        }
    }

    // --- 2. Collect body children of root (non-Module, non-Variable) ---
    QVector<const SceneDocument::TreeNode *> bodyChildren;
    QVector<const SceneDocument::TreeNode *> moduleChildren;
    for (const SceneDocument::TreeNode &child : scene.treeRoot().children) {
        if (child.type == SceneDocument::TreeNode::Group
            && child.operation == SceneDocument::TreeNode::Module)
            moduleChildren.append(&child);
        else if (child.type != SceneDocument::TreeNode::Variable)
            bodyChildren.append(&child);
    }

    // --- 3. If there are body children, wrap them in the implicit scene_model ---
    const bool hasImplicitModule = !bodyChildren.isEmpty() || scene.treeRoot().children.isEmpty();
    if (hasImplicitModule) {
        if (!moduleChildren.isEmpty() || !scene.treeRoot().children.isEmpty())
            *code += "\n";
        const int moduleStart = code->size();
        *code += "module scene_model() {\n";
        if (bodyChildren.isEmpty()) {
            *code += "    // Add shapes from the tree editor.\n";
        } else {
            for (const SceneDocument::TreeNode *child : bodyChildren)
                appendTreeNode(code, *child, scene, "    ", ranges);
        }
        *code += "}\n";
        if (ranges)
            ranges->append({scene.treeRoot().id, moduleStart, code->size() - moduleStart});
    }

    // --- 4. Emit each named Module child ---
    for (const SceneDocument::TreeNode *mod : moduleChildren) {
        *code += "\n";
        const int moduleStart = code->size();
        *code += QString("module %1 {\n").arg(moduleSignature(*mod));

        for (const SceneDocument::TreeNode &child : mod->children) {
            if (child.type == SceneDocument::TreeNode::Variable && child.isParameter)
                continue; // params already in signature, not in body
            appendTreeNode(code, child, scene, "    ", ranges);
        }

        *code += "}\n";
        if (ranges)
            ranges->append({mod->id, moduleStart, code->size() - moduleStart});
    }

    // --- 5. Calls ---
    *code += "\n";
    if (hasImplicitModule)
        *code += "scene_model();\n";
    for (const SceneDocument::TreeNode *mod : moduleChildren)
        *code += mod->moduleName.trimmed() + "();\n";
}

void OpenScadGenerator::appendTreeNode(QString *code,
                                       const SceneDocument::TreeNode &node,
                                       const SceneDocument &scene,
                                       const QString &indent,
                                       QVector<SourceRange> *ranges)
{
    const int start = code->size();

    if (node.type == SceneDocument::TreeNode::Primitive) {
        if (const ShapeNode *shape = scene.shapeById(node.shapeId)) {
            appendShape(code, *shape, indent);
            if (ranges)
                ranges->append({node.id, start, code->size() - start});
        }
        return;
    }

    if (node.type == SceneDocument::TreeNode::Variable) {
        *code += QString("%1%2 = %3;\n")
                     .arg(indent, node.variableName)
                     .arg(node.variableExpression.trimmed().isEmpty()
                              ? QString::number(node.variableValue)
                              : node.variableExpression.trimmed());
        if (ranges)
            ranges->append({node.id, start, code->size() - start});
        return;
    }

    // Module nodes are emitted as top-level definitions by appendSceneModule;
    // if one appears nested (shouldn't happen), fall through to generic group handling.
    if (node.operation == SceneDocument::TreeNode::Module) {
        for (const SceneDocument::TreeNode &child : node.children)
            appendTreeNode(code, child, scene, indent, ranges);
        if (ranges && code->size() > start)
            ranges->append({node.id, start, code->size() - start});
        return;
    }

    if (node.operation == SceneDocument::TreeNode::For) {
        const QString variableName = node.loopVariable.trimmed().isEmpty()
                                         ? QStringLiteral("i")
                                         : node.loopVariable.trimmed();
        const QString rangeExpression = node.loopRangeExpression.trimmed().isEmpty()
                                            ? QStringLiteral("[0 : 1 : 3]")
                                            : node.loopRangeExpression.trimmed();
        *code += QString("%1for (%2 = %3) {\n").arg(indent, variableName, rangeExpression);

        for (const SceneDocument::TreeNode &child : node.children)
            appendTreeNode(code, child, scene, indent + "    ", ranges);

        *code += indent + "}\n";
        if (ranges)
            ranges->append({node.id, start, code->size() - start});
        return;
    }

    if (node.operation == SceneDocument::TreeNode::Translate
        || node.operation == SceneDocument::TreeNode::Rotate
        || node.operation == SceneDocument::TreeNode::Scale) {
        QString transformName = QStringLiteral("scale");
        QVector3D transformVector = node.scale;
        if (node.operation == SceneDocument::TreeNode::Translate) {
            transformName = QStringLiteral("translate");
            transformVector = node.position;
        } else if (node.operation == SceneDocument::TreeNode::Rotate) {
            transformName = QStringLiteral("rotate");
            transformVector = node.rotation;
        }
        auto txExpr = [&](int axis, float numericValue) -> QString {
            if (axis < node.transformExpressions.size() && !node.transformExpressions[axis].isEmpty())
                return node.transformExpressions[axis];
            return QString::number(numericValue, 'g');
        };
        *code += QString("%1%2([%3, %4, %5]) {\n")
                     .arg(indent, transformName)
                     .arg(txExpr(0, transformVector.x()),
                          txExpr(1, transformVector.y()),
                          txExpr(2, transformVector.z()));

        for (const SceneDocument::TreeNode &child : node.children)
            appendTreeNode(code, child, scene, indent + "    ", ranges);

        *code += indent + "}\n";
        if (ranges)
            ranges->append({node.id, start, code->size() - start});
        return;
    }

    appendTreeGroup(code, treeOperationName(node.operation), node, scene, indent, ranges);
    if (ranges)
        ranges->append({node.id, start, code->size() - start});
}

void OpenScadGenerator::appendTreeGroup(QString *code,
                                        const QString &name,
                                        const SceneDocument::TreeNode &node,
                                        const SceneDocument &scene,
                                        const QString &indent,
                                        QVector<SourceRange> *ranges)
{
    *code += QString("%1%2() {\n").arg(indent, name);

    for (const SceneDocument::TreeNode &child : node.children)
        appendTreeNode(code, child, scene, indent + "    ", ranges);

    *code += indent + "}\n";
}

QString OpenScadGenerator::shapeToOpenScad(const ShapeNode &shape)
{
    auto paramExpr = [&](int idx, qreal numericValue) -> QString {
        if (idx < shape.parameterExpressions.size() && !shape.parameterExpressions[idx].isEmpty())
            return shape.parameterExpressions[idx];
        return QString::number(numericValue, 'g');
    };

    if (shape.type == ShapeNode::Cube) {
        return QString("cube([%1, %2, %3], center=true);\n")
            .arg(paramExpr(0, shape.size.x()))
            .arg(paramExpr(1, shape.size.y()))
            .arg(paramExpr(2, shape.size.z()));
    }
    if (shape.type == ShapeNode::Sphere) {
        return QString("sphere(r=%1);\n")
            .arg(paramExpr(0, shape.radius));
    }
    if (shape.type == ShapeNode::Cylinder) {
        // parameterExpressions: index 0 = R (radius), index 1 = H (height)
        return QString("cylinder(h=%1, r=%2, center=true);\n")
            .arg(paramExpr(1, shape.height))
            .arg(paramExpr(0, shape.radius));
    }
    return QString();
}
