#include "openscadgenerator.h"

#include <QStringList>

void OpenScadGenerator::appendShape(QString *code, const ShapeNode &shape, const QString &indent)
{
    const QString shapeCode = shapeToOpenScad(shape);
    const QStringList lines = shapeCode.split('\n');

    for (const QString &line : lines) {
        if (!line.trimmed().isEmpty())
            *code += indent + line + "\n";
    }
}

QString OpenScadGenerator::generate(const SceneDocument &scene)
{
    QString code;

    code += "// Generated by OpenSCAD Visual Editor Prototype\n";
    code += "// UI -> OpenSCAD code\n\n";

    if (scene.isEmpty()) {
        code += "// Add shapes from the left panel.\n";
        return code;
    }

    appendTreeNode(&code, scene.treeRoot(), scene, "");
    return code;
}

static QString treeOperationName(SceneDocument::TreeNode::Operation operation)
{
    if (operation == SceneDocument::TreeNode::Difference)
        return "difference";
    if (operation == SceneDocument::TreeNode::Intersection)
        return "intersection";
    return "union";
}

void OpenScadGenerator::appendTreeNode(QString *code, const SceneDocument::TreeNode &node, const SceneDocument &scene, const QString &indent)
{
    if (node.type == SceneDocument::TreeNode::Primitive) {
        if (const ShapeNode *shape = scene.shapeById(node.shapeId))
            appendShape(code, *shape, indent);
        return;
    }

    appendTreeGroup(code, treeOperationName(node.operation), node, scene, indent);
}

void OpenScadGenerator::appendTreeGroup(QString *code,
                                        const QString &name,
                                        const SceneDocument::TreeNode &node,
                                        const SceneDocument &scene,
                                        const QString &indent)
{
    *code += QString("%1%2() {\n").arg(indent, name);

    for (const SceneDocument::TreeNode &child : node.children)
        appendTreeNode(code, child, scene, indent + "    ");

    *code += indent + "}\n";
}

QString OpenScadGenerator::shapeToOpenScad(const ShapeNode &shape)
{
    QString code;

    code += QString("translate([%1, %2, %3])\n")
                .arg(shape.position.x())
                .arg(shape.position.y())
                .arg(shape.position.z());

    code += QString("rotate([%1, %2, %3])\n")
                .arg(shape.rotation.x())
                .arg(shape.rotation.y())
                .arg(shape.rotation.z());

    if (shape.type == ShapeNode::Cube) {
        code += QString("cube([%1, %2, %3], center=true);\n")
                    .arg(shape.size.x())
                    .arg(shape.size.y())
                    .arg(shape.size.z());
    } else if (shape.type == ShapeNode::Sphere) {
        code += QString("sphere(r=%1);\n")
                    .arg(shape.radius);
    } else if (shape.type == ShapeNode::Cylinder) {
        code += QString("cylinder(h=%1, r=%2, center=true);\n")
                    .arg(shape.height)
                    .arg(shape.radius);
    }

    return code;
}
