// Generated by OpenSCAD Visual Editor Prototype
// UI -> OpenSCAD code

module scene_model() {
    for (i = [0 : 1 : 3]) {
        translate([0, i*50, 0]) {
            difference() {
                cube([115, 20, 20], center=true);
                for (i = [0 : 1 : 3]) {
                    translate([i*10, 0, 0]) {
                        cylinder(h=30, r=4, center=true);
                    }
                }
            }
        }
    }
}

scene_model();
