// Generated by OpenSCAD Visual Editor Prototype
// UI -> OpenSCAD code

arm_length = 38;
arm_width = 5;
arm_height = 3;
motor_radius = 7;
motor_height = 4;
prop_radius = 13;
prop_thickness = 1.2;

module body() {
    cube([28, 28, 4], center=true);
}

module arm(angle = 0) {
    rotate([0, 0, angle]) {
        translate([arm_length / 2, 0, 0]) {
            cube([arm_length, arm_width, arm_height], center=true);
        }
    }
}

module motor_mount(angle = 0) {
    rotate([0, 0, angle]) {
        translate([arm_length, 0, 0]) {
            cylinder(h=motor_height, r=motor_radius, center=true);
            difference() {
                cylinder(h=motor_height + 0.2, r=motor_radius, center=true);
                cylinder(h=motor_height + 0.4, r=2.2, center=true);
            }
        }
    }
}

module propeller(angle = 0) {
    rotate([0, 0, angle]) {
        translate([arm_length, 0, motor_height / 2 + 1.2]) {
            union() {
                cube([prop_radius * 2, 3, prop_thickness], center=true);
                cube([3, prop_radius * 2, prop_thickness], center=true);
                cylinder(h=prop_thickness + 0.2, r=2.5, center=true);
            }
        }
    }
}

module landing_foot(x = 0, y = 0) {
    translate([x, y, -5]) {
        cylinder(h=8, r=1.2, center=true);
    }
}

module modular_drone() {
    union() {
        body();
        for (a = [45, 135, 225, 315]) {
            arm(a);
            motor_mount(a);
            propeller(a);
        }
        landing_foot(9, 9);
        landing_foot(-9, 9);
        landing_foot(9, -9);
        landing_foot(-9, -9);
    }
}

modular_drone();
